[project]
name = "deepseek-comparer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.2.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "ruff>=0.9.7",
]
